CREATE DATABASE [REPLACEME] CONTAINMENT = NONE 
ON PRIMARY
( NAME = N'REPLACEME', FILENAME = N'E:\SQL_DATA\REPLACEME.mdf' , SIZE = 30GB , FILEGROWTH = 512GB )
LOG ON ( NAME = N'REPLACEME_Log', FILENAME = N'F:\SQL_LOG\REPLACEME_log.ldf' , SIZE = 10GB, FILEGROWTH = 256MB )
GO
ALTER DATABASE [REPLACEME] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [REPLACEME] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [REPLACEME] SET ANSI_NULLS OFF
GO
ALTER DATABASE [REPLACEME] SET ANSI_PADDING OFF
GO
ALTER DATABASE [REPLACEME] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [REPLACEME] SET ARITHABORT OFF
GO
ALTER DATABASE [REPLACEME] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [REPLACEME] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [REPLACEME] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [REPLACEME] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [REPLACEME] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [REPLACEME] SET CURSOR_DEFAULT GLOBAL
GO
ALTER DATABASE [REPLACEME] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [REPLACEME] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [REPLACEME] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [REPLACEME] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [REPLACEME] SET DISABLE_BROKER
GO
ALTER DATABASE [REPLACEME] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [REPLACEME] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [REPLACEME] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [REPLACEME] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [REPLACEME] SET READ_WRITE
GO
ALTER DATABASE [REPLACEME] SET RECOVERY SIMPLE
GO
ALTER DATABASE [REPLACEME] SET MULTI_USER
GO
ALTER DATABASE [REPLACEME] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [REPLACEME] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [REPLACEME] SET DELAYED_DURABILITY = DISABLED
GO


USE [REPLACEME]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE [REPLACEME]
GO
IF NOT EXISTS (SELECT name
	FROM sys.filegroups
	WHERE is_default=1
		AND name = N'PRIMARY')
ALTER DATABASE [REPLACEME] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

ALTER DATABASE [REPLACEME]
SET RECOVERY Simple
 